import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :itsm, ItsmWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :itsm, ItsmWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      # paths: ["/health"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger,
  backends: [:console, {LoggerFileBackend, :itsm_log}]

# 로그파일 설정은 컴파일 타임에서 인자값을 받을수 있음 (jenkins에서 설정가능함)
log_file_name = System.get_env("LOG_FILE_NAME") || "itsm.log"
log_level = if System.get_env("LOG_FILE_NAME"), do: :debug, else: :info

config :logger, :itsm_log,
  path: "/fslog/sqe/" <> log_file_name,
  level: log_level,
  format: "$date $time [$level] $metadata $message\n",
  metadata: [:request_id, :mfa, :pid, :user_id]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
